CREATE TABLE trz_vc_opt.od_t_opt_power_cap_market_by_area_auc_cont_rslt (
    cont_rslt_rls_date DATE NOT NULL COMMENT '約定結果の公表日',
    target_fiscal_year NUMBER(4,0) NOT NULL COMMENT '対象実需給年度',
    auc_type_name VARCHAR(255) NOT NULL COMMENT 'メインオークション / 追加オークション 等の種別',
    area_code VARCHAR(2) NOT NULL COMMENT 'TSOの供給区域を示すコード',
    area_name VARCHAR(255) COMMENT 'TSOの供給区域の名称',
    area_unitprice NUMBER(38,2) COMMENT 'エリア毎の単価',
    cont_cap_volume NUMBER(38,2) COMMENT 'エリア毎の約定容量',
    after_ded_cont_ttl_amount NUMBER(38,2) COMMENT '経過措置控除を反映させた、エリア毎の約定総額',
    url_text VARCHAR COMMENT '諸元のURL',
    product_id VARCHAR(255) COMMENT 'データの識別子',
    ubis_data_id VARCHAR(6) NOT NULL COMMENT '各データ指標を識別するID',
    ind_name VARCHAR(255) NOT NULL COMMENT '指標名',
    ind_jpn_name VARCHAR(255) NOT NULL COMMENT '指標名_日本語',
    data_creator_id VARCHAR(6) NOT NULL COMMENT 'データ諸元ID',
    data_creator_name VARCHAR(255) NOT NULL COMMENT 'データ諸元名',
    process_flag BOOLEAN NOT NULL COMMENT '加工したデータかを判別',
    aggregation_unit VARCHAR(255) NOT NULL COMMENT 'データがどの程度の詳細度で集計されているかを識別する',
    cale_id VARCHAR(6) NOT NULL COMMENT 'カレンダーID',
    cale_name VARCHAR(255) NOT NULL COMMENT 'カレンダー名',
    if_id VARCHAR(255) NOT NULL COMMENT 'インターフェースID',
    if_file_name VARCHAR(255) NOT NULL COMMENT 'IFファイル名',
    if_row_number NUMBER(38,0) NOT NULL COMMENT 'IF行番号',
    created_by VARCHAR(255) COMMENT '作成者',
    create_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコードの作成日時',
    update_at TIMESTAMP_LTZ(7) COMMENT 'レコードの更新日時',
    process_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコード作成／更新処理の実行日時',
    process_id VARCHAR(255) NOT NULL COMMENT 'レコード作成／更新処理を特定するID',
    PRIMARY KEY (cont_rslt_rls_date, target_fiscal_year, auc_type_name, area_code, ubis_data_id)
) WITH DATA_RETENTION_TIME_IN_DAYS = 30;