CREATE TABLE dlz.dl_t_opt_power_area_gen_charge_unit_price (
    apply_start_fiscal_year VARCHAR COMMENT '発電側課金制度の適用開始年度',
    apply_end_fiscal_year VARCHAR COMMENT '発電側課金制度の適用終了年度',
    area_name VARCHAR COMMENT 'エリア名称(東京電力PGは東京、中部電力PGは中部で付与)',
    basic_charge_unitprice VARCHAR COMMENT '系統連携受電サービス料金の内、全電圧の基本料金',
    island_basic_charge_unitprice VARCHAR COMMENT '系統連携受電サービス料金の内、全電圧の基本料金(離島の利用者)',
    elec_energy_charge_unitprice VARCHAR COMMENT '系統連携受電サービス料金の内、全電圧の電力量料金',
    A1_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額A-1',
    A2_over140kv_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額A-2(受電電圧が標準電圧140kV をこえる場合)',
    A2_under140kv_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額A-2(受電電圧が標準電圧140kV 以下の場合)',
    A3_over140kv_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額A-3(受電電圧が標準電圧140kV をこえる場合)',
    A3_under140kv_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額A-3(受電電圧が標準電圧140kV 以下の場合)',
    B1_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額B-1',
    B2_dscnt_amount VARCHAR COMMENT '系統設備効率化割引額B-2',
    url_text VARCHAR COMMENT '諸元のURL',
    product_id VARCHAR COMMENT 'データの識別子',
    if_id VARCHAR COMMENT 'インターフェースID',
    if_file_name VARCHAR(255) NOT NULL COMMENT 'IFファイル名',
    if_row_number NUMBER(38,0) NOT NULL COMMENT 'IF行番号',
    created_by VARCHAR COMMENT '作成者',
    create_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコードの作成日時',
    update_at TIMESTAMP_LTZ(7) COMMENT 'レコードの更新日時',
    process_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコード作成／更新処理の実行日時',
    process_id VARCHAR(255) NOT NULL COMMENT 'レコード作成／更新処理を特定するID',
    PRIMARY KEY (apply_start_fiscal_year, apply_end_fiscal_year, area_name)
) WITH DATA_RETENTION_TIME_IN_DAYS = 30;