CREATE TABLE dlz.連系線_空容量_年間計画 (
    target_class VARCHAR COMMENT '対象断面',
    formulate_year VARCHAR COMMENT '策定年度／年',
    updated_class VARCHAR COMMENT '策定／更新後',
    interconn_name VARCHAR COMMENT '連系線',
    target_date VARCHAR COMMENT '年月日',
    timeframe_value VARCHAR COMMENT '昼／夜',
    dirct_value VARCHAR COMMENT '方向',
    avail_cap_min_value VARCHAR COMMENT '空容量最小',
    avail_cap_max_value VARCHAR COMMENT '空容量最大',
    plan_load_flow_value VARCHAR COMMENT '計画潮流',
    margin_b_max_value VARCHAR COMMENT 'マージンA最大',
    margin_a_min_value VARCHAR COMMENT 'マージンA最小',
    margin_b_value VARCHAR COMMENT 'マージンB',
    grid_cap_value VARCHAR COMMENT '運用容量',
    grid_cap_detrmt_text VARCHAR COMMENT '運用容量決定要因',
    enlarge_plan_load_flow_value VARCHAR COMMENT '運用容量拡大分空容量',
    enlarge_grid_cap_value VARCHAR COMMENT '運用容量拡大分運用容量',
    supply_ng_number VARCHAR COMMENT '送電NG情報件数',
    supply_ng_stated_cap_value VARCHAR COMMENT '送電NG情報延べ容量',
    source_update_at VARCHAR COMMENT '最新更新年月日時刻',
    url_text VARCHAR COMMENT '諸元のURL',
    product_id VARCHAR COMMENT 'データの識別子',
    if_id VARCHAR COMMENT 'インターフェースID',
    if_file_name VARCHAR(255) NOT NULL COMMENT 'IFファイル名',
    if_row_number NUMBER(38,0) NOT NULL COMMENT 'IF行番号',
    created_by VARCHAR COMMENT '作成者',
    create_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコードの作成日時',
    update_at TIMESTAMP_LTZ(7) COMMENT 'レコードの更新日時',
    process_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコード作成／更新処理の実行日時',
    process_id VARCHAR(255) NOT NULL COMMENT 'レコード作成／更新処理を特定するID',
    PRIMARY KEY (if_file_name, if_row_number)
) DATA_RETENTION_TIME_IN_DAYS = 30 COMMENT 'OCCTOから取得した連系線の月間断面の空容量の計画(策定/更新後)を格納するテーブル';