CREATE TABLE dlz.dl_t_opt_interconn_load_flow_actl (
    interconn_name VARCHAR COMMENT '連系線の名称',
    target_date VARCHAR COMMENT '潮流実績の対象日',
    target_time_text VARCHAR COMMENT '潮流実績の対象時刻',
    forward_grid_cap_value VARCHAR COMMENT '連系線（順方向）に流せる電力量（潮流）の上限値',
    reverse_grid_cap_value VARCHAR COMMENT '連系線（逆方向）に流せる電力量（潮流）の上限値',
    forward_wide_area_adjst_value VARCHAR COMMENT '電力需給バランスを広域的に調整する力（順方向）',
    reverse_wide_area_adjst_value VARCHAR COMMENT '電力需給バランスを広域的に調整する力（逆方向）',
    forward_margin_value VARCHAR COMMENT '連系線（順方向）を通じて、電力の需給バランスを広域的に調整するために設定される容量枠',
    reverse_margin_value VARCHAR COMMENT '連系線（逆方向）を通じて、電力の需給バランスを広域的に調整するために設定される容量枠',
    forward_avail_cap_value VARCHAR COMMENT '不測の事態の裕度として予め確保している連系線（順方向）の運用容量',
    reverse_avail_cap_value VARCHAR COMMENT '不測の事態の裕度として予め確保している連系線（逆方向）の運用容量',
    forward_plan_load_flow_value VARCHAR COMMENT '連系線（順方向）に流す電力量の計画値',
    reverse_plan_load_flow_value VARCHAR COMMENT '連系線（逆方向）に流す電力量の計画値',
    load_flow_value VARCHAR COMMENT '連系線に流した電力量の実績値',
    forward_enlarge_grid_cap_value VARCHAR COMMENT '緊急時において広げることが可能な連系線（順方向）の運用容量',
    reverse_enlarge_grid_cap_value VARCHAR COMMENT '緊急時において広げることが可能な連系線（逆方向）の運用容量',
    url_text VARCHAR COMMENT '諸元のURL',
    product_id VARCHAR COMMENT 'データの識別子',
    if_id VARCHAR COMMENT 'インターフェースID',
    if_file_name VARCHAR(255) NOT NULL COMMENT 'IFファイル名',
    if_row_number NUMBER(38,0) NOT NULL COMMENT 'IF行番号',
    created_by VARCHAR COMMENT 'レコードの作成者',
    create_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコードの作成日時',
    update_at TIMESTAMP_LTZ(7) COMMENT 'レコードの更新日時',
    process_at TIMESTAMP_LTZ(7) NOT NULL COMMENT 'レコード作成／更新処理の実行日時',
    process_id VARCHAR(255) NOT NULL COMMENT 'レコード作成／更新処理を特定するID',
    PRIMARY KEY (interconn_name, target_date, target_time_text)
) WITH DATA_RETENTION_TIME_IN_DAYS = 30;